package Capstone.SpringSqlServer;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import Capstone.SpringSqlServer.GPS;
import Capstone.SpringSqlServer.GPSRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called gpsRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private GPSRepository gpsRepository;



    @GetMapping(path="/all")
    @Autowired
    public @ResponseBody Iterable<GPS> getAllCoordinates() {
        // This returns a JSON or XML with the users
        return gpsRepository.findAll();
    }
}